<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>S2</RootNamespace>
	<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('macOS'))">
    <DefineConstants>$(DefineConstants);MACCATALYST</DefineConstants>
  </PropertyGroup>
  
  <Import Project="..\..\Ixian-Core\IXICore.projitems" Label="Shared" />
  
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="FluentCommandLineParser-netstandard" Version="1.4.3.13" />
    <PackageReference Include="Mono.Nat" Version="3.0.4" />
    <PackageReference Include="RocksDB" Version="10.4.2.64152" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  
  <PropertyGroup>
    <ApplicationIcon>IxianS2.ico</ApplicationIcon>
    <AssemblyName>IxianS2</AssemblyName>
    <AssemblyTitle>Ixian S2</AssemblyTitle>
    <AssemblyDescription></AssemblyDescription>
    <AssemblyCompany>Ixian</AssemblyCompany>
    <Product>Ixian S2</Product>
    <Copyright>Copyright © 2026 Ixian</Copyright>
    <VersionPrefix>0.9.5.2</VersionPrefix>
    <PackageProjectUrl>https://www.ixian.io</PackageProjectUrl>
    <CLSCompliant>true</CLSCompliant>
    <ComVisible>false</ComVisible>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Include="IxianS2.ico" />
  </ItemGroup>
  
  <Target Name="CopyHTMLToOutput" AfterTargets="CoreCompile">
    <ItemGroup>
      <IXIPB1 Include="$(SolutionDir)\..\Ixian-Core\html\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(IXIPB1)" DestinationFolder="$(OutputPath)\html\%(RecursiveDir)" ContinueOnError="true" />
  </Target>
</Project>