name: .NET

on:
  push:
    branches: [ 'master', 'development' ]

defaults:
  run:
    working-directory: Ixian-S2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ixian-S2
      uses: actions/checkout@v2
      with:
        path: Ixian-S2

    - name: Checkout Ixian-Core
      uses: actions/checkout@v2
      with:
        repository: ixian-platform/Ixian-Core
        path: Ixian-Core
        ref: ${{ github.event.push.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Building Ixian-S2
      run: dotnet build

    #- name: Running Unit Tests
    #  run: dotnet test UnitTests\bin\Debug\unittests.dll --verbosity normal
